title: Marietta Fischesser-Metze
# tagline: A content-first minimalist Jekyll theme for blogs
description: A brief overview.

author:
  name:   Florian Metze
  url:    http://www.cs.cmu.edu/~fmetze/interACT/Home.html
  avatar: https://avatars.githubusercontent.com/u/97170774

plugins:
  - jekyll-paginate

# paginate: 2

categories_path: /categories/
tags_path: /tags/
